# Introduction

::: {.callout-warning}

This book is a **work in progress**, please bear with me as I update and fix the issues.

If you have any particular examples you'd like to be included please let me know @ c.jonestodd@auckland.ac.nz

:::

The `stelfi` package fits Hawkes and log-Gaussian Cox Point Process models, with extensions, using Template Model Builder (@tmb).

**Overview**

A Hawkes process is a self-exciting temporal point process where the occurrence of an event immediately increases the chance of another (see @hawkes). `stelfi` also offers functionality to fit self-inhibiting process and a non-homogeneous background rate.


A log-Gaussian Cox process is a Poisson point process where the log-intensity is given by a Gaussian random field. `stelfi` also offers functionality to extend this to a joint likelihood formulation fitting a marked log-Gaussian Cox model.


In addition, the `stelfi` offers functionality to fit self-exciting  spatiotemporal point processes. Models are fitted via maximum likelihood  using 'TMB' (Template Model Builder) (@tmb). Where included 1) random fields are assumed to be Gaussian and are integrated over using the Laplace approximation and  2) a stochastic partial differential equation model, introduced by @spde, is defined for the field(s).
