---
title: "Spatiotemporal point process models"
author: "Charlotte M. Jones-Todd"
date: ""
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Spatiotemporal process models}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE,message=FALSE,results='asis'}
knitr::opts_chunk$set(eval = TRUE, warning = FALSE, message = FALSE, cache = TRUE)
knitr::read_chunk("st.r")
```

To install the `R` package `stelfi` run `devtools::install_github("cmjt/stelfi")`. Use `devtools::install_github("cmjt/stelfi",build_vignettes = TRUE)` if you want to build vignettes at the same time.

```{r,libs,echo = TRUE}
```

## A point process model for terrorism attacks perpetrated by ISIL in Iraq, 2013--2017


```{r,data_iq,echo = TRUE}
```

```{r,maps,echo = TRUE}
```

```{r,plot,echo = FALSE, fig.width = 8,fig.height = 5,fig.cap = "Point pattern of attacks by ISIL in Iraq, 2013--2017"}
```

```{r,mesh,echo = TRUE}
```
 

### `INLA`

```{r,model_inla,echo = TRUE}
```

```{r,fixed_effects,echo = TRUE}
```

```{r,random_effects,echo = TRUE, fig.width = 10,fig.height = 7.5,fig.cap = "Estimated mean of the random fields, 2013--2017"}
```


### `TMB`

**TODO**