---
title: ""
output: 
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE,message=FALSE,results='asis'}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE,cache = TRUE)
```


## Fitting a Hawkes process to Twitter data

```{r load data,results='hide',message=FALSE}
library(stelfi)
data(retweets_niwa)
```

```{r sort data}
time <- retweets_niwa
## numeric time stamps
times <- as.numeric(difftime(time,min(time),units = "hour"))
```

```{r fit model,results='hide',cache=TRUE}
params <- c(mu = 50,alpha = 3,beta = 6)
## must have compiled TMB templates first use compile.stelfi()
fit <- fit.hawkes(times = times,parameters = params,upper = c(100,5,15),lower = c(0,0,0))
rep <- TMB::sdreport(fit)
par <- summary(rep)[,1]
```

```{r params}
## print out estimated parameters
par
```


```{r plot, echo = FALSE,fig.height=7.5,fig.width=10,fig.cap="Fitted intensity (top plot) and observed counts of retweets (bottom)."}
## NIWA seal first tweet according to Twitter
start <- lubridate::ymd_hms("2019-02-05 02:27:07")
## NIWA seal found owner tweet according to Twitter
end <- lubridate::ymd_hms("2019-02-07 06:50:08")
p <- seq(min(times),max(times),length.out = 1000)
intenst <- stelfi:::hawke.intensity(mu = par[1],alpha = par[2],beta = par[3],times = times, p = p)
layout(matrix(c(1,1,1,1,1,1,2,2,2),byrow = TRUE, ncol = 3))
par(mar = c(1,5,1,2))
plot(times,rep(0,length(time)),pch = "|", yaxt = "n",ylab = "", xlab = "", ylim = c(0,max(intenst)),
     xaxt = "n",cex = 0.6)
mtext(2,line = 0,text = "Rate of retweets per hour", cex = 0.9)
lines(p,intenst,col = "grey")
axis(2,at = round(c(0,max(intenst)),2),las = 2)
const <- length(times)/max(times)
abline(h = const, lty = 2)
text(35,const + 50, paste("Constant rate of",round(const,2),"retweets per hour"))
arrows(35,const + 45, 35,const,length = 0.05)
day2 <- start + 24*60*60
day3 <- day2 + 24*60*60
abline(v = as.numeric(difftime(day2,min(time),unit = "hours")))
text(as.numeric(difftime(day2,min(time),unit = "hours")) - 1,130,"24hrs since tweet",srt = 90)
abline(v = as.numeric(difftime(day3,min(time),unit = "hours")))
text(as.numeric(difftime(day3,min(time),unit = "hours")) - 1,130,"48hrs since tweet",srt = 90)
par(mar = c(2,5,0,2))
## hist
hist(time, breaks = "hours", axes = FALSE, xlab = "", ylab = "",main = "", col = "grey",border = "grey",freq = TRUE)
axis(2,at = c(0,250))
mtext(2, line = 0, text = "Number of retweets per hour",cex = 0.8)
mtext(1,line = 1, at = c(start,end),text = c("NIWA \n tweeted","USB owner \n found"),cex = 0.9)
```
