# Key `stelfi` functions

#### Summary of model fitting functions offered and lists the key arguments for each. {-}

+-----------------------+-------------------------------------------------------+
| **Function**          | **Key arguments**                                     | 
+:======================+:======================================================+
| `fit_hawkes()`        | -   `times` - a vector of `numeric` occurrence times. | 
|                       |                                                       | 
|                       | -   `parameters` - a vector of named starting values  |                       
|                       |     for $\mu$ (`mu`), $\alpha$ (`alpha`), and         |                       
|                       |     $\beta$ (`beta`).                                 |                       
|                       |                                                       |                       
|                       | -   `marks` -  optional, a  vector of marks ($m(t)$). |                       
+-----------------------+-------------------------------------------------------+
| `fit_hawkes_cbf()`    | As `fit_hawkes()` plus                                | 
|                       |                                                       | 
|                       | -   `background` -  some assumed time dependent       | 
|                       |     background function $\mu(t)$.                     |                       
|                       |                                                       |                       
|                       | -   `background_integral` -  the integral of          |                       
|                       |     `background`.                                     |                       
|                       |                                                       |                       
|                       | -   `background_parameters` - parameter               |                       
|                       |     starting values for $\mu(t)$.                     |                       
|                       |                                                       |                       
|                       | ( $^*$Note, $\texttt{mu}$ in  `parameters` will be    |                       
|                       | ignored)                                              |                       
+-----------------------+-------------------------------------------------------+
| `fit_lgcp()`          | -   `locs` - a named data frame of  event locations,  | 
|                       |     `x`, `y`, and `t` (optional).                     | 
|                       |                                                       | 
|                       | -   `sf` - a polygon  of the spatial domain.          | 
|                       |                                                       | 
|                       | -   `smesh` - a Delaunay triangulation of the spatial |                       
|                       |     domain returned by  `INLA::inla.mesh.2d()`.       |                       
|                       |                                                       |                       
|                       | -   `tmesh` - optional, a temporal mesh returned by   |                       
|                       |     `INLA::inla.mesh.1d()`).                          |                       
|                       |                                                       |                       
|                       | -   `parameters` - a vector of named starting values  |                       
|                       |     for $\boldsymbol{\beta}$ (`beta`),               |                       
|                       |     $\text{log}(\tau)$ (`log_tau`),                   |                     
|                       |     $\text{log}(\kappa)$ (`log_kappa`), and           |                       
|                       |     $\textrm{arctan}(\rho)$  (`atanh_rho`, optional). |                       
+-----------------------+-------------------------------------------------------+
| `fit_mlgcp()`         | -   `locs`, `sf`, and `smesh` - as  `fit_lgcp()`.     | 
|                       |                                                       | 
|                       | -   `marks` - a  matrix of marks for each             |                       
|                       |     observation of the point pattern.                 |                       
|                       |                                                       |                       
|                       | -   `parameters` - a  list of named parameters, as    |                       
|                       |     `fit_lgcp()` plus (`betamarks`),  (`betapp`),     |                       
|                       |     (`marks_coefs_pp` ).                              |                       
|                       |                                                       |                     
|                       | -   `methods` -  integer(s)  specifying mark          |                       
|                       |     distribution: `0`, Gaussian;  `1`, Poisson;       |                       
|                       |     `2`, binomial; `3`, gamma.                        |                     
|                       |                                                       |                       
|                       | -   `strfixed` - fixed structural  parameters,        |                       
|                       |     depends on mark  distribution.                    |                       
|                       |                                                       |                       
|                       | -   `fields` - a  binary vector   indicating          |                       
|                       |     whether there is  a new random field for each     |                       
|                       |     mark.                                             |                       
+-----------------------+-------------------------------------------------------+
| `fit_stelfi()`        | -   `times` - as  `fit_hawkes()`.                     | 
|                       |                                                       | 
|                       | -   `locs`, `sf`, and `smesh` - as `fit_lgcp()`.      |           
|                       |                                                       |                       
|                       | -   `parameters` - a list of named  parameter         |                       
|                       |     starting values for $\mu$ (`mu`), $\alpha$        |                       
|                       |     (`alpha`), $\beta$ (`beta`), $\sigma_x$ (`xsigma`)|                       
|                       |     $\sigma_y$  (`ysigma`), and  $\rho$ (`rho`).      |                       
|                       |                                                       |                       
|                       | -   `GMRF` - logical, should a GMRF be included as a  |                       
|                       |     latent spatial effect if so $\tau$ (`tau`)        |                       
|                       |     and $\kappa$(`kappa`) supplied to `parameters`.   |                       
+-----------------------+-------------------------------------------------------+



#### Summary of utility and simulation functions listing the key arguments for each. {-}

+-----------------------+-----------------------+-----------------------+
| **Function**          | **Key arguments**     | **Purpose**           |
+:======================+:======================+:======================+
| `get_coefs()`         | -   `obj` - a fitted  | Extract estimated     |
|                       |     model object      | parameter values from |
|                       |     returned by any   | a fitted model.       |
|                       |     one of the        |                       |
|                       |     functions in the  |                       |
|                       |     Table  above      |                       |
+-----------------------+-----------------------+-----------------------+
| `get_fields()`        | As `fit_lgcp()` and   | Extract estimated     |
|                       |                       | mean, or standard     |
|                       | -   `sd` - logical,   | deviation, of         |
|                       |     return standard   | GMRF(s).              |
|                       |     deviation.        |                       |
+-----------------------+-----------------------+-----------------------+
| `get_weights()`       | -   `mesh` - a        | Calculate mesh        |
|                       |     Delaunay          | weights.              |
|                       |     triangulation of  |                       |
|                       |     the spatial       |                       |
|                       |     domain returned   |                       |
|                       |     by                |                       |
|                       |     `INLA::inla.mesh. |                       |
|                       | 2d()`.                |                       |
|                       |                       |                       |
|                       | -   `sf` - a polygon  |                       |
|                       |     of the spatial    |                       |
|                       |     domain.           |                       |
+-----------------------+-----------------------+-----------------------+
| `mesh_2_sf()`         | -   `mesh` - a        | Transforms `mesh`     |
|                       |     Delaunay          | into a `sf` object.   |
|                       |     triangulation of  |                       |
|                       |     the spatial       |                       |
|                       |     domain returned   |                       |
|                       |     by                |                       |
|                       |     `INLA::inla.mesh. |                       |
|                       | 2d()`.                |                       |
+-----------------------+-----------------------+-----------------------+
| `show_field()`        | -   `x` - a vector of | Plots spatial random  |
|                       |     values, one per   | field values.         |
|                       |     each smesh node.  |                       |
|                       |                       |                       |
|                       | -   `smesh` - as      |                       |
|                       |     `fit_lgcp()` .    |                       |
|                       |                       |                       |
|                       | -   `sf` - as         |                       |
|                       |     `fit_lgcp()`.     |                       |
|                       |                       |                       |
|                       | -   `clip` - logical, |                       |
|                       |     *clip* to domain  |                       |
+-----------------------+-----------------------+-----------------------+
| `show_hawkes()`       | -   `obj` - a fitted  | Plot fitted Hawkes    |
|                       |     model object      | model.                |
|                       |     returned by       |                       |
|                       |     `fit_hawkes()` or |                       |
|                       |     `fit_hawkes_cbf() |                       |
|                       | `.                    |                       |
+-----------------------+-----------------------+-----------------------+
| `show_hawkes_GOF()`   | -   `obj` - as        | Plot goodness-of-fit  |
|                       |     `show_hawkes()`.  | metrics for a Hawkes  |
|                       |                       | model.                |
|                       | -   `plot` - logical  |                       |
|                       |                       |                       |
|                       | -   `return_values` - |                       |
|                       |     logical, return   |                       |
|                       |     compensator       |                       |
|                       |     values            |                       |
+-----------------------+-----------------------+-----------------------+
| `show_lambda()`       | As `fit_lgcp()` and   | Plot estimated        |
|                       |                       | spatial intensity     |
|                       | -   `clip` - logical, | from a fitted         |
|                       |     *clip* to domain  | log-Gaussian Cox      |
|                       |                       | process model.        |
+-----------------------+-----------------------+-----------------------+
| `sim_hawkes()`        | As `fit_hawkes()`     | Simulate a Hawkes     |
|                       |                       | process.              |
+-----------------------+-----------------------+-----------------------+
| `sim_lgcp()`          | As `fit_lgcp()`       | Simulate a            |
|                       |                       | realisation of a      |
|                       |                       | log-Gaussian Cox      |
|                       |                       | process.              |
+-----------------------+-----------------------+-----------------------+


