# log-Gaussian Cox Process {#lgcp}

## The `fit_lgcp()` function

```{r}
args(fit_lgcp)
```

## Fitting a LGCP

### Spatial only

```{r}
require(maptools)
data(xyt, package = "stelfi")
domain <- as(xyt$window, "SpatialPolygons")
locs <- data.frame(x = xyt$x, y = xyt$y)
smesh <- INLA::inla.mesh.2d(boundary = INLA::inla.sp2segment(domain), 
                      max.edge = 0.75, cutoff = 0.3)
system.time(fit <- fit_lgcp(locs = locs, sp = domain, smesh = smesh,
                            parameters = c(beta = 0, log_tau = log(1), log_kappa = log(1))))
get_coefs(fit)
```

```{r}
plot_lambda(fit, smesh = smesh, border = domain) +
    ggplot2::theme_void()
```

**Comparing to `inlabru`**

```{r}
require(inlabru)
require(ggplot2)
matern <- INLA::inla.spde2.matern(smesh)
cmp <- coordinates ~ mySmooth(coordinates, model = matern) + Intercept(1)
coordinates(locs) <- c("x", "y")
system.time(fit_inla <- lgcp(cmp, locs,
                             samplers = domain,
                             domain = list(coordinates = smesh),
                             options = list(control.inla = list(int.strategy = "eb"))))
summary(fit_inla)
```

```{r, echo = FALSE, results = 'asis'}
lambda <- predict(fit_inla, pixels(smesh), ~ exp(mySmooth + Intercept))
ggplot() +
    gg(lambda) +
    gg(domain) +
    coord_fixed() +
    scale_fill_viridis_c() +
    theme_void()


```

### Spatiotemporal LGCP

```{r}
ndays <- 2
locs <- data.frame(x = xyt$x, y = xyt$y, t = xyt$t)
w0 <- 2
tmesh <- INLA::inla.mesh.1d(seq(0, ndays, by = w0))
fit <- fit_lgcp(locs = locs, sp = domain, smesh = smesh, tmesh = tmesh,
                parameters = c(beta = 0, log_tau = log(1), log_kappa = log(1), atanh_rho = 0.2))
get_coefs(fit)
```


```{r}

plot_lambda(fit, smesh = smesh, tmesh = tmesh, timestamp = 1, title = "t = 1") +
    ggplot2::theme_void()
plot_lambda(fit, smesh = smesh, tmesh = tmesh, timestamp = 2, title = "t = 2") +
    ggplot2::theme_void()

```

