# Spatiotemporal self-exciting model {#stelfi}

## The `fit_stelfi()` function

```{r}
args(fit_stelfi)
```

## Hawkes spatial

```{r, eval = FALSE}
data(xyt)
N = 50
locs <- cbind(x = xyt$x[1:N], y = xyt$y[1:N])
times <- xyt$t[1:N]
loc.d <- cbind(c(0, 13, 13, 0, 0), c(-3, -3, 3, 3, -3))
domain <- sp::SpatialPolygons(list(sp::Polygons(list(sp::Polygon(loc.d)),'0')))
smesh <- INLA::inla.mesh.2d(boundary = INLA::inla.sp2segment(domain), 
                            max.edge = 0.75, cutoff = 0.3)
param <- list( mu = 3, alpha = 1, beta = 3, xsigma = 0.2,
             ysigma = 0.2, rho = 0.8)
t_stelfi <- system.time(fit <- fit_stelfi(times = times, locs = locs, sp = domain, smesh = smesh, parameters = param,
                  gaussian = TRUE, simple = 1))
print(t_stelfi)
get_coefs(fit)
```


## Hawkes spde

```{r, eval = FALSE}

## issues with time....
param <- list( mu = 5, alpha = 1, beta = 3, kappa = 0.9, tau = 1,
              xsigma = 0.2,
              ysigma = 0.2, rho = 0.8)
fit <- fit_stelfi(times = times, locs = locs, sp = domain,
                  smesh = smesh, parameters = param,
                  gaussian = FALSE)
get_coefs(fit)
```