--- 
title: "The `R` package `stelfi`"
author: "Charlotte M. Jones-Todd & Alec van Helsdingen"
date: ""
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Using `stelfi`"
---


# Installation {-}

The development version of `stelfi` package can be installed from GitHub:

```{r eval=FALSE}
devtools::install_github("cmjt/stelfi")
```

The `stelfi` package requires installation of the non-CRAN package `INLA`. To install `INLA` use

```{r, eval = FALSE}
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
```

If you have any issues please follow [these instructions](https://www.r-inla.org/download-install).

```{r include = FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
knitr::opts_chunk$set(cache = TRUE, message = FALSE, warning = FALSE)
```
